Route REST requests to back-end services (#508)
Each REST request is now routed to the appropriate back-end service based on its HTTP annotation path. The server now outputs a log message confirming the request was received. Note, however, that no request parameters are populated yet, so most requests FAIL (returning an error code back over REST responses). Populating request parameters comes next.

This adds a dependency on the gorilla/mux dispatcher.

**Running locally:**
To build and test:
`go install ./util/cmd/... && go run ./util/cmd/compile_protos && go test ./... && go install ./...`

To run the server, as usual:
`gapic-showcase run`

Local REST output:
```
$ curl http://localhost:7469/v1beta1/echo:echo  
{}

$ curl http://localhost:7469/v1beta1/echo:expand
ERROR: not implementing streaming methods yet                                                                                                                 

$ curl http://localhost:7469/v1beta1/users/someone/profile/blurbs
rpc error: code = NotFound desc = Parent  not found. 
```

**Review notes:**
- `server/genrest/` contains the generated files, which are large but may be useful for seeing what gets generated. The actual code is in other directories, mainly `util/genrest/`
- there are no tests for the generated files yet, since the content will change in upcoming PRs.